' assignment 3 - revc'

# Original DNA sequence
dna_sequence = "TTGTTAAGGTTTGACTCTCGGAACTCGCTGCGCCAGGCGAGGTAACTTCGCACAAACGGAGTGTATCACCCCCGTTAGAATACGCGATCTCACCAAGGGCACGACTGAGCTGCGCATTCTCTGTAAGTCACCTAAAATCTTAGAGGGACTGGGGCTGCATATGTGTATAAGTGCGCGTTAACGATCAGTCTGATCTATTATTCTAGGCAACTGGGGATTGCGAGATCTCGGTGCTAGCTGTTTCTCTGAGAGCGCATGAAGGAGCCTACTTCTAGGAGCCAGCCATGACAGAACTGAGTTCAGTTTACATTCTGTTTTCGCGCACCAAACAAGTTTCGTTACCTCGGGATATGCAGACCTTCGGTAATCGCTACGGATTGTACCGCCAGTGAGGGCATCCATCTGCTGTATGTAGCCAAATTAGAGGGGACTTTGCGAATTCTTGGTTGTTTACGAGTTGTTGTGAGACTGTTATCAAAAGCCATTGTTTCCACCGTAGAATGATGTGTTTCGGCGTATAATGCTTAAGCTCTGTCCGTGGGAAAGAGACGCCCTCCGGCGCGCCACGCTGTAAGTGCCCGTGGATTCCGACAGGTTCTGCGGACCGGATGTAGGTGACTATAAGGTCCTCGGCCGAGAGATTGCCAAGCCCTAACTGTCTTCTTCTAAGAAACTGCGTATATTTTACTTGTTGCCCCTGGAGCGAGAGGAAGTCGAGTGATGTCCTAGGGCAGCTAGGCATTCGACTCCCGAGAGTCAGAAGATAGGGCCCGGGCGCCGATATCGGCTCATACATTGCATCATAGGCCCGTTATTGCATTACGTCGATAACACTTCCATCAAAGGCATAAAGAGCAGTCAAAGACGA"

# Dictionary to map each base to its complement
complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}

# Get the complement of each base in the sequence
complemented_sequence = ''.join([complement[base] for base in dna_sequence])

# Reverse the complemented sequence
reverse_complement = complemented_sequence[::-1]

# Display the reverse complement
print(reverse_complement)
