'6- tran'

def transition_transversion_ratio(s1, s2):
    # Count transitions and transversions
    transitions = 0
    transversions = 0

    for base1, base2 in zip(s1, s2):
        if base1 != base2:  # Only consider differences
            if (base1 in "AG" and base2 in "AG") or (base1 in "CT" and base2 in "CT"):
                transitions += 1
            else:
                transversions += 1

    # Calculate the transition/transversion ratio
    if transversions == 0:
        return float('inf')  # Or define how to handle this case
    else:
        return transitions / transversions

if __name__ == "__main__":
    # DNA strings #s1 >Rosalind_7956 #s2 >Rosalind_4003
    s1 = "ATTGGCACCATCGCACCTAGGCTCTCACATCGTTATTAAGCGCTGCATAATTGTCGAATGGGCCACCTGTACCGTGGAACACGTAGTGCTTCTGTCGCCATAAACTAGGGTGCTATTGGAATCCGAGCCACCCGACGATGCGAGGCTTTGGCACTAGGGAAGTCCGAGATGGCTTCATATTAGCACACTTAATTGTACCTAGCGAAGAATTGTTTGGTAAGAGAAATTTCTTATCGGAATATGAGTATTCCTCGAAAGGGCCTTAGTCGGCAGCCCTGCCGACGCATAAAATGGTTTTCCTCAGCATCTATTGCTGGACCTGGAGGGCGGGCTAGTCATGGGGCTGGTCGCGAAGGTCACCGCCGGTGATTTTGCCACACACACGTAATCTGCTTTAGGTGGACATACGATCAGAGGAACTGCGGCGTACCGCACCCGTTAGCGCATTACTGCCGAAAATATAAAGAGCGAACGTAGGAGTCACGACAGCAGTGTGGGAGGGATGAGCGATAGTAGAGGCGCATTCTGCGCCTAAGCCATTATTTATATATTCACAGTTCGGTAACGGGCAGGGGCCTTGTCCCCACCACCCTTGCGCTTCGAGGATTTTGCTTGGCAGCTGAATGCGTGGGTCGCACTGCCAGTAGATTAACTCCCGAGACCGTCGTTGTTGATTGCGAATCATCTCCGGTTCGGCCTTGTCCGGTGACCTGCCCGGAGACCCACTATCTTACCTATTGGGCCGAGCAATAACCGCTTAGGCCTTGCGCCCCTCTCAGGACAGGATCCATGCCTGAGTGGAAACGAGAAGCTCCGCCACGCAATTGCGAGTTTTAATGTGCAGAACGGCGCGGAATCTAGAGAAGACGG"
    s2 = "ATTAACACCATCACACTTAGGCTCTCACACCATTGTTAGGTGGCGGGTAATTGTGAAATAGACCGTCTATACCATGGAACAGGCAGTGCTTCCGGCTCCATAAACTAAGATGTTGTTGTAATCCAGACCGTCCGACAACTCAAGGCTGTAACATTCGGGAAGTTCAAGACGGCTTCACGTTAGCATACTTAATAGTGGCTGGTGGAGCGTTGTGCAATGACCGGGACTACTTCTCGGAAGATGAGCATCCCTTGAGATATTCTTAGTCGGCAATCCTGCCAACGCGTAGAATATTTTGTCCCAGCACTTATTACTGGACTTGAGTGACGGACGGGTCATGAGGTTGGCCACGTAGGTTATCGCCGGCGGCTTTCCGACATACACACAGTCGGTCTTGCGTGTACACACGACCACGGAAACTGCGGCGTACCGCACCCATTGGCGCAGCCCTACAGAAAATAAGGAAACCTAACATAGAAGTAGCGACAGCATCATACGAGAGGGGAACGATAGTAGAGGCACATTCTGCGCCTGGGCGCTTCCCCATATCCTCACAATTCGGTGACGAGCAGGGGCCGTGTTTCGACCACCAGTGTGCGTCGGGGGCTTCGCTTGGTAATTGACTACATGCGTTGCAACGCCCGGAGATCAAGTTCGGAGACCGTTGTTGTTCATTGCGGGTCATCCCCGATTCGGCCTTGTCCAATGACTTACCCGGGGACCTACTATCACACTCTGTGGGCCGAACAGTACCCCCTAAGACCTCGACTCCTTCCCAAAACGAGGTCCACATTCGAGTAGCAACGTGGAACTCCGCTCCGCAATTGCAACTTTTAATACGCAAAACAGCGCGAAGTACAGAGAAGACTG"




    # Calculate the ratio
    ratio = transition_transversion_ratio(s1, s2)
    print(f"Transition/Transversion Ratio: {ratio}")
